name: Python Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: make install

      - name: Lint Python
        run: make lint_python

      - name: Spell Check Python
        run: make spell_check

      - name: Format Python
        run: make format_python
